# Generated by Django 4.1.4 on 2023-02-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='i18nsection',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
