# Generated by Django 4.1.4 on 2023-02-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_i18nsection_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='i18nsection',
            name='language',
            field=models.CharField(default='en', max_length=12),
        ),
        migrations.AddField(
            model_name='i18nsection',
            name='translation_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
