# Generated by Django 4.1.4 on 2023-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blogpost_content_alter_blogpost_slug_alter_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='i18nsection',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='language',
            field=models.CharField(default='en', max_length=12),
        ),
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(default='en', max_length=12),
        ),
        migrations.DeleteModel(
            name='PageSection',
        ),
    ]
