# Generated by Django 4.1.4 on 2023-02-02 22:17

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0002_alter_blogpost_content_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='I18nSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_id', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(default='en', max_length=12)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_id', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
                ('language', models.CharField(default='en', max_length=12)),
                ('text', mdeditor.fields.MDTextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['content_type', 'object_id'], name='pages_pages_content_ffefd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagesection',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='pages_pagesection_unique_per_language'),
        ),
    ]
