# Generated by Django 4.1.4 on 2023-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_blogpost_content_remove_page_content_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_id',
            new_name='translation_id',
        ),
        migrations.AddField(
            model_name='section',
            name='language',
            field=models.CharField(default='en', max_length=12),
        ),
    ]
