version: "3.8"
services:
  frontend:
    container_name: app-frontend
    ports:
      - 3000:3000
    user: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    depends_on:
      - backend
    networks:
      - bridge-network
    volumes:
      - ./frontend:/app
    env_file: .env.local
    command: bash -c "npm run dev"

  backend:
    container_name: app-backend
    ports:
      - 8000:8000
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/src
    networks:
      - brid2023-01-09T22:21:20.649 app[3e9d6560] yyz [info] return request("post", url, data=data, json=json, **kwargs)

ge-network
    depends_on:
      - db
    env_file: .env.local
    command: python3 manage.py runserver 0.0.0.0:8000

  meilisearch:
    container_name: meilisearch
    restart: always
    ports:
      - 7700:7700
    build:
      context: ./search
      dockerfile: Dockerfile
    volumes:
      - /meili_data:/meili_data
    networks:
      - bridge-network
    env_file: .env.local

  db:
    image: postgres:14-bullseye
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - bridge-network
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env.local

volumes:
  postgres:
    name: postgres-db

networks:
  bridge-network:
    driver: bridge
