version: '3.8'
services:
  frontend:
    container_name: app-frontend
    ports:
      - '3000:3000'
    user: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - db
    env_file:
      - .env.local
  
  db:
    image: postgres:14-bullseye
    container_name: postgres
    restart: always
    env_file:
      - .env.local
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  keystone:
    image: node:lts-bullseye-slim
  

volumes:
  postgres:
    name: postgres-db