version: "3.8"
services:
  frontend:
    container_name: app-frontend
    ports:
      - "3000:3000"
    user: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - db
    networks:
      - bridge-network

  meilisearch:
    container_name: meilisearch
    restart: always
    ports:
      - 7700:7700
    build:
      context: ./search
      dockerfile: Dockerfile
    volumes:
      - /meili_data:/meili_data
    networks:
      - bridge-network
    env_file: .env.local

  db:
    image: postgres:14-bullseye
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bridge-network

volumes:
  postgres:
    name: postgres-db

networks:
  bridge-network:
    driver: bridge