version: "3.8"
services:
  frontend:
    container_name: app-frontend
    ports:
      - "3000:3000"
    user: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - db
    networks:
      - bridge-network

  strapi:
    container_name: strapi
    restart: unless-stopped
    ports:
      - '1337:1337'
    build:
      context: ./admin
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - bridge-network

  db:
    image: postgres:14-bullseye
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - bridge-network

volumes:
  postgres:
    name: postgres-db

networks:
  bridge-network:
    driver: bridge