# Generated by Django 4.1.4 on 2023-02-23 18:02

from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeilisearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=15)),
                ('displayed_attributes', models.JSONField(decoder=list, default=list)),
                ('searchable_attributes', models.JSONField(decoder=list, default=list)),
                ('filterable_attributes', models.JSONField(decoder=list, default=search.models._filterable_attributes_default)),
                ('stop_words', models.JSONField(decoder=list, default=list)),
                ('synonyms', models.CharField(max_length=20, null=True)),
                ('typo_tolerance', models.JSONField(default=search.models._typo_tolerance_default)),
                ('faceting', models.JSONField(default=search.models._faceting_default)),
                ('pagination', models.JSONField(default=search.models._pagination_default)),
                ('cfg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.meilisearchconfig')),
            ],
        ),
    ]
