# Generated by Django 4.1.4 on 2023-02-23 18:15

from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeilisearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=search.models._default_config)),
                ('_rel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.meilisearchconfig')),
            ],
        ),
    ]
