# Generated by Django 4.1.4 on 2023-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_not_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchindex',
            options={'verbose_name_plural': 'Search Indexes'},
        ),
        migrations.AddField(
            model_name='searchindex',
            name='index_name',
            field=models.CharField(default='/services', max_length=15),
            preserve_default=False,
        ),
    ]
