# Generated by Django 4.1.4 on 2023-07-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_searchindex__rel'),
    ]

    operations = [
    ]
