# Generated by Django 4.1.4 on 2022-12-27 02:40

from django.db import migrations, models
import functools
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('blurb', models.CharField(blank=True, max_length=255)),
                ('description', mdeditor.fields.MDTextField(blank=True)),
                ('phone_numbers', models.JSONField(default=functools.partial(dict, *({'primary': None},), **{}))),
                ('socials', models.JSONField(default=functools.partial(dict, *({'twitter': None},), **{}))),
                ('hours', models.JSONField(default=functools.partial(dict, *({'Friday': None, 'Monday': None, 'Saturday': None, 'Sunday': None, 'Thursday': None, 'Tuesday': None, 'Wednesday': None, 'extra': None},), **{}))),
                ('_contact', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
