# Generated by Django 4.1.4 on 2022-12-26 23:26

from django.db import migrations, models
import django_jsonform.models.fields
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('blurb', models.CharField(max_length=255)),
                ('description', mdeditor.fields.MDTextField()),
                ('phone_numbers', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=31), size=None)),
                ('socials', django_jsonform.models.fields.JSONField()),
                ('hours', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=31), size=7)),
                ('extra', django_jsonform.models.fields.JSONField()),
                ('_contact', models.TextField()),
            ],
        ),
    ]
