# Generated by Django 4.1.4 on 2023-02-01 23:54

from django.db import migrations, models
import django.db.models.deletion
import django_admin_geomap
import functools
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_id', models.CharField(max_length=31, unique=True)),
                ('_description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FacetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('extra', models.JSONField(blank=True, default=functools.partial(dict, *({},), **{}))),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.facet')),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_virtual', models.BooleanField(default=True, verbose_name='virtual?')),
                ('website', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('blurb', models.CharField(blank=True, max_length=255)),
                ('description', mdeditor.fields.MDTextField(blank=True)),
                ('phone_numbers', models.JSONField(blank=True, default=functools.partial(dict, *({'primary': None},), **{}), help_text="Example keys: 'primary', 'emergency', etc.")),
                ('socials', models.JSONField(blank=True, default=functools.partial(dict, *({'twitter': None},), **{}), help_text="Example keys: 'twitter', 'instagram', etc.", verbose_name='Social media')),
                ('hours', models.JSONField(blank=True, default=functools.partial(dict, *({'Friday': None, 'Monday': None, 'Saturday': None, 'Sunday': None, 'Thursday': None, 'Tuesday': None, 'Wednesday': None, 'extra': None},), **{}), help_text="Example keys: 'monday', 'tuesday', 'note', 'alert', etc.", verbose_name='Opening hours')),
                ('extra', models.JSONField(blank=True, default=functools.partial(dict, *({},), **{}))),
                ('_contact', models.CharField(blank=True, max_length=255)),
                ('tags', models.ManyToManyField(through='services.FacetTag', to='services.facet')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='FacetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_id', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
                ('language', models.CharField(default='en', max_length=12)),
                ('value', models.CharField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facettag',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddIndex(
            model_name='facettranslation',
            index=models.Index(fields=['content_type', 'object_id'], name='services_fa_content_1ba548_idx'),
        ),
        migrations.AddConstraint(
            model_name='facettranslation',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='services_facettranslation_unique_per_language'),
        ),
        migrations.AddConstraint(
            model_name='facettag',
            constraint=models.UniqueConstraint(fields=('service', 'facet', 'value'), name='unique_tag'),
        ),
    ]
