# Generated by Django 4.1.4 on 2022-12-28 02:20

from django.db import migrations, models
import django.db.models.deletion
import functools
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='hours',
            field=models.JSONField(blank=True, default=functools.partial(dict, *({'Friday': None, 'Monday': None, 'Saturday': None, 'Sunday': None, 'Thursday': None, 'Tuesday': None, 'Wednesday': None, 'extra': None},), **{})),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=functools.partial(dict, *({'primary': None},), **{})),
        ),
        migrations.AlterField(
            model_name='service',
            name='socials',
            field=models.JSONField(blank=True, default=functools.partial(dict, *({'twitter': None},), **{})),
        ),
        migrations.CreateModel(
            name='FacetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=31)),
                ('extra', models.JSONField(blank=True, default=functools.partial(dict, *({},), **{}))),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.facet')),
                ('service', models.ForeignKey(on_delete=models.SET(services.models.Service.sentinel), to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(through='services.FacetTag', to='services.facet'),
        ),
    ]
