# Generated by Django 4.1.4 on 2022-12-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hours',
            field=models.JSONField(default={'default': {'Friday': None, 'Monday': None, 'Saturday': None, 'Sunday': None, 'Thursday': None, 'Tuesday': None, 'Wednesday': None, 'extra': None}}),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_numbers',
            field=models.JSONField(default={'default': {'primary': None}}),
        ),
        migrations.AlterField(
            model_name='service',
            name='socials',
            field=models.JSONField(default={'default': {'twitter': None}}),
        ),
    ]
