# Generated by Django 4.1.4 on 2022-12-26 23:43

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='_contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='hours',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_numbers',
            field=django_jsonform.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
