# Generated by Django 4.1.4 on 2022-12-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_facet_alter_service_hours_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facettag',
            constraint=models.UniqueConstraint(fields=('service', 'facet', 'value'), name='unique_tag'),
        ),
    ]
