# Generated by Django 4.1.4 on 2022-12-27 01:08

from django.db import migrations, models
import services.schemas


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_hours_alter_service_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hours',
            field=models.JSONField(default=services.schemas.hours),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_numbers',
            field=models.JSONField(default=services.schemas.phone_numbers),
        ),
        migrations.AlterField(
            model_name='service',
            name='socials',
            field=models.JSONField(default=services.schemas.socials),
        ),
    ]
