# Generated by Django 4.1.4 on 2022-12-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_facettag_unique_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='facet',
            name='translation_id',
            field=models.CharField(default=None, max_length=31, unique=True),
            preserve_default=False,
        ),
    ]
