# Generated by Django 4.1.4 on 2022-12-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_facet__description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facet',
            name='_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
