# Generated by Django 4.1.4 on 2022-12-31 02:48

from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_facettag_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facettag',
            name='unique_tag',
        ),
        migrations.AlterField(
            model_name='service',
            name='hours',
            field=models.JSONField(blank=True, default=functools.partial(dict, *({'Friday': None, 'Monday': None, 'Saturday': None, 'Sunday': None, 'Thursday': None, 'Tuesday': None, 'Wednesday': None, 'extra': None},), **{}), help_text="Example keys: 'monday', 'tuesday', 'note', 'alert', etc.", verbose_name='Opening hours'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=functools.partial(dict, *({'primary': None},), **{}), help_text="Example keys: 'primary', 'emergency', etc."),
        ),
        migrations.AlterField(
            model_name='service',
            name='socials',
            field=models.JSONField(blank=True, default=functools.partial(dict, *({'twitter': None},), **{}), help_text="Example keys: 'twitter', 'instagram', etc.", verbose_name='Social media'),
        ),
        migrations.AddConstraint(
            model_name='facettag',
            constraint=models.UniqueConstraint(models.F('service'), models.F('facet'), models.F('value'), name='unique_tag'),
        ),
    ]
