# Generated by Django 4.1.4 on 2022-12-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_facettag_unique_tag_alter_service_hours_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facettag',
            name='unique_tag',
        ),
        migrations.AddConstraint(
            model_name='facettag',
            constraint=models.UniqueConstraint(fields=('service', 'facet', 'value'), name='unique_tag'),
        ),
    ]
