# Generated by Django 4.1.4 on 2023-01-03 19:10

from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='service',
            name='extra',
            field=models.JSONField(blank=True, default=functools.partial(dict, *({},), **{})),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
