# Generated by Django 4.1.4 on 2023-01-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_email_service_extra_service_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facettag',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='facettag',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
