# Generated by Django 4.1.4 on 2023-01-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_facettag_service_alter_facettag_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
