# Generated by Django 4.1.4 on 2023-01-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_service_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.AddField(
            model_name='service',
            name='is_virtual',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='services.service')),
            ],
        ),
    ]
