# Generated by Django 4.1.4 on 2023-02-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0014_alter_service_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.AddField(
            model_name='service',
            name='is_virtual',
            field=models.BooleanField(default=True, verbose_name='virtual?'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='FacetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_id', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
                ('language', models.CharField(default='en', max_length=12)),
                ('value', models.CharField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='facettranslation',
            index=models.Index(fields=['content_type', 'object_id'], name='services_fa_content_1ba548_idx'),
        ),
        migrations.AddConstraint(
            model_name='facettranslation',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='services_facettranslation_unique_per_language'),
        ),
    ]
