# Generated by Django 4.1.4 on 2023-02-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_service_address_service_is_virtual_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('id',)},
        ),
        migrations.DeleteModel(
            name='FacetTranslation',
        ),
    ]
