# Generated by Django 4.1.4 on 2023-01-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_service_address_service_is_virtual_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
