# Generated by Django 4.1.4 on 2023-01-19 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_location_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='services.service'),
        ),
    ]
