# Generated by Django 4.1.4 on 2023-09-01 00:51

import uuid
from django.db import migrations


def set_meili(apps, schema_editor):
    meili_config = apps.get_model("search", "MeilisearchConfig").objects.get()
    from search import client
    indexes = meili_config.indexes.all()
    for index in indexes:
        client.index(index.index_name).update_settings(index.config)


def populate_meili(apps, schema_editor):
    cls = apps.get_model("services", "Service")
    from search import client
    from django.utils.text import Truncator

    published_services = cls.objects.filter(published=True)

    settings = client.index('services').get_settings()

    searchable_fields = settings.get('searchableAttributes', [])
    if searchable_fields == ['*']:
        raise NotImplemented

    documents = []

    for service in published_services:
        flat_tags = [{
            'id': tag.id,
            tag.facet.translation_id: tag.value
        } for tag in service.tags.all()]

        fields = {
            field: getattr(service, field)
            for field in searchable_fields
        }

        documents.append({
            'id': service.id,
            **fields,
            'tags': flat_tags
        })

    client.refresh('services', documents)

    # other databases
 
    facets = apps.get_model("services", "Facet")
    tags = apps.get_model("services", "FacetTag")
    i18n = apps.get_model("pages", "I18nSection")

    settings = client.index('facets').get_settings()
    searchable_fields = settings.get('searchableAttributes', [])

    documents = []

    names = {

    }

    for facet in facets.objects.all():
        values = tags.objects.filter(
            facet=facet,
            service__published=True
        )\
        .order_by('value')\
        .distinct('value')\
        .values_list('value', flat=True)

        names[facet.translation_id] = i18n.objects.get(
            translation_id=f'tags.{facet.translation_id}',
            language="en"
        ).text

        documents.append({
            'id': facet.translation_id,
            **{field: getattr(facet, field, None) for field in searchable_fields},
            'value': list(values),
            'name': names[facet.translation_id]
        })

    client.refresh('facets', documents)

    documents = []

    qs = set(tags.objects.values_list('facet__translation_id', 'value'))

    for translation_id, value in qs:
        
        sanitized_value = "".join(
            char for char in value.lower() if char.isascii() and char.isalpha()
        )[:16]

        documents.append({
            "id": f'{uuid.uuid4().hex[:8]}-{sanitized_value}',
            "facet": {
                "translation_id": translation_id,
                "name": names[translation_id]
            },
            "value": value
        })

    client.refresh('tags', documents)

    # geodata

    subset_with_location = cls.objects.filter(
        published=True, location__isnull=False)

    documents = [{
        "slug": service.slug,
        "name": service.name,
        "blurb": Truncator(service.description).chars(60),
        "_geo": {
            "lat": service.location.latitude,
            "lng": service.location.longitude
        }} for service in subset_with_location]

    client.refresh('geodata', documents, primary_key='slug')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_service_tags_alter_facettag_service_and_more'),
    ]

    operations = [
        migrations.RunPython(set_meili),
        migrations.RunPython(populate_meili)
    ]
