# Generated by Django 4.1.4 on 2023-01-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_location_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_virtual',
            field=models.BooleanField(default=True, verbose_name='virtual?'),
        ),
    ]
