# Generated by Django 4.1.4 on 2023-01-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0019_alter_service_is_virtual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facet',
            name='translation_id',
        ),
        migrations.CreateModel(
            name='FacetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_id', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='facettranslation',
            index=models.Index(fields=['content_type', 'object_id'], name='services_fa_content_1ba548_idx'),
        ),
    ]
