# Generated by Django 4.1.4 on 2023-01-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_facet_translation_id_facettranslation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facettranslation',
            name='language',
            field=models.CharField(default='en', max_length=12),
        ),
    ]
