# Generated by Django 4.1.4 on 2023-01-31 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0022_facet_translation_id_delete_facettranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facet',
            name='translation_id',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.CreateModel(
            name='FacetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_id', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
                ('language', models.CharField(default='en', max_length=12)),
                ('value', models.CharField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='facettranslation',
            index=models.Index(fields=['content_type', 'object_id'], name='services_fa_content_1ba548_idx'),
        ),
    ]
