name: Deploy Preview App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - beta


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: yyz
  FLY_ORG: personal

  # env-name template: preview-${{ github.event.number }}

jobs:
  # TODO: would https://github.com/dorny/paths-filter#conditional-execution
  # cause desync/unknown variables?
  env_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create preview slug
        id: preview_slug
        env:
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "PREVIEW_SLUG=${PR_NUMBER}-${BRANCH_NAME/\//-}" >> ${GITHUB_OUTPUT}
    outputs:
      slug: 
        value: ${{ steps.preview_slug.PREVIEW_SLUG }}

  preview_deploy:
    runs-on: ubuntu-latest

    needs: [env_setup]

    concurrency:
      group: preview-${{ github.event.number }}

    environment:
      name: preview-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    env:
      prefix: ${{ needs.env_setup.outputs.slug }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Meilisearch
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          update: false # don't redeploy when PR is updated
          path: search
          name: ${{ env.prefix }}-meilisearch
      
      - name: Deploy backend
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          path: backend
          name: ${{ env.prefix }}-django
          postgres: ${{ secrets.DEV_DB_APP_NAME }}

      - name: Deploy frontend
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          path: frontend
          name: ${{ env.prefix }}-frontend
  
  teardown_on_failure:
    if: ${{ failure() }}
    needs: [env_setup, preview_deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - env:
          ENV_NAME: ${{ needs.env_setup.outputs.slug }}
        run: |
          flyctl apps destroy -y $ENV_NAME-meilisearch; \
          flyctl apps destroy -y $ENV_NAME-django; \
          flyctl apps destroy -y $ENV_NAME-frontend

  # Clean up environment on PR close
  cleanup_environment:
    if: ${{ always() && github.event.action == 'closed' }}
    needs: [env_setup, preview_deploy, teardown_on_failure]
    runs-on: ubuntu-latest
    steps:
    - uses: strumwolf/delete-deployment-environment@v2.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: preview-${{ github.event.number }}
