name: Deploy Preview App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: yyz
  FLY_ORG: personal

  # env-name template: preview-${{ github.event.number }}

jobs:
  preview_deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: preview-${{ github.event.number }}

    environment:
      name: preview-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Meilisearch
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          update: false # don't redeploy when PR is updated
          path: search
          name: preview-${{ github.event.number }}-meilisearch
      
      - name: Deploy backend
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          path: backend
          name: preview-${{ github.event.number }}-django
          postgres: ${{ secrets.DEV_DB_APP_NAME }}

      - name: Deploy frontend
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          path: frontend
          name: preview-${{ github.event.number }}-frontend

      - name: Teardown apps on failure
        if: ${{ failure() }}
        uses: superfly/flyctl-actions/setup-flyctl@master
        env:
          ENV_NAME: preview-${{ github.event.number }}
        run: |
          flyctl apps destroy -y $ENV_NAME-meilisearch; \
          flyctl apps destroy -y $ENV_NAME-django; \
          flyctl apps destroy -y $ENV_NAME-frontend

  # Clean up environment on PR close
  cleanup_environment:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
    - uses: strumwolf/delete-deployment-environment@v2.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: preview-${{ github.event.number }}
