name: Deploy Preview App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - beta

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: yyz
  FLY_ORG: personal

jobs:
  # TODO: would https://github.com/dorny/paths-filter#conditional-execution
  # cause desync/unknown variables?
  env_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create preview slug
        id: preview_slug
        env:
          PR_NUMBER: ${{ github.event.number }}
          BRANCH_NAME: ${{ github.head_ref }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          CLEAN_BRANCH=${BRANCH_NAME//\//-}
          echo "CLEAN_BRANCH=${CLEAN_BRANCH}" >> ${GITHUB_OUTPUT}
          echo "PREVIEW_SLUG=${PR_NUMBER}-${CLEAN_BRANCH}-${COMMIT_SHA:0:8}" >> ${GITHUB_OUTPUT}
    outputs:
      clean_branch: ${{ steps.preview_slug.outputs.CLEAN_BRANCH }}
      slug: ${{ steps.preview_slug.outputs.PREVIEW_SLUG }}

  preview_deploy:
    runs-on: ubuntu-latest

    needs: [env_setup]

    # env-name template: preview-${{ github.event.number }}
    concurrency:
      group: preview-${{ github.event.number }}

    environment:
      name: preview-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    env:
      prefix: ${{ needs.env_setup.outputs.slug }}
      meili_key: ${{ needs.env_setup.outputs.slug}}-staging-meili-key
      db_name: ${{ needs.env_setup.outputs.clean_branch }}-staging

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Meilisearch
        run: |
          cd search
          flyctl launch \
            --name ${prefix}-meilisearch \
            --no-deploy \
            --build-only \
            --copy-config \
            --now \
            --no-deploy \
            --remote-only \
            --region $FLY_REGION \
            --org $FLY_ORG \
            ;
            
          flyctl deploy \
            --app ${prefix}-meilisearch \
            --config fly.toml \
            --remote-only \
            --strategy immediate \
            --region $FLY_REGION \
            --env MEILI_MASTER_KEY=${meili_key} \
            --env MEILI_HTTP_ADDR=localhost:7700 \
            ;
            
          cd ..

      - name: Provision Postgres cluster
        run: |
          if ! flyctl status --app $db_name &> /dev/null; then
          flyctl postgres create \
            --name $db_name \
            --fork-from community-maps-db \
            --vm-size shared-cpu-1x \
            --volume-size 1 \
            --initial-cluster-size 1 \
            --region $FLY_REGION \
            --org $FLY_ORG \
            | awk '1;/Postgres cluster/{exit}'
          fi

      - name: Deploy Django
        env:
          appname: ${{ env.prefix }}-django
        run: |
          cd backend

          echo "::group::Launch and build app"
          flyctl launch \
            --name $appname \
            --no-deploy \
            --build-only \
            --copy-config \
            --now \
            --no-deploy \
            --remote-only \
            --region $FLY_REGION \
            --org $FLY_ORG \
            ;
          echo "::endgroup::"

          echo "::group::Attach to postgres"
          flyctl postgres attach \
            $db_name \
            --app $appname \
            --database-user "user_${appname//-/_}" \
            --database-name "community_maps_django" \
            --verbose \
            --yes \
            ;
          echo "::endgroup::"

          echo "::group::Deploy and release"
          flyctl deploy \
            --app $appname \
            --config fly.toml \
            --remote-only \
            --strategy immediate \
            --region $FLY_REGION \
            --env DJANGO_SETTINGS_MODULE=api.settings.staging \
            --env ALLOWED_HOSTS=${appname}.fly.dev \
            --env CSRF_TRUSTED_ORIGINS=https://${appname}.fly.dev \
            --env MEILISEARCH_HOST=https://${prefix}-meilisearch.fly.dev \
            --env MEILISEARCH_KEY=${meili_key} \
            ;
          echo "::endgroup::"

          cd ..

      - name: Deploy Next
        env:
          appname: ${{ env.prefix }}
        run: |
          cd frontend
          
          api_host=https://${prefix}-django.fly.dev
          meili_host=https://${prefix}-meilisearch.fly.dev
          host=https://${prefix}.fly.dev

          flyctl launch \
            --name $appname \
            --copy-config \
            --now \
            --remote-only \
            --strategy immediate \
            --region $FLY_REGION \
            --org $FLY_ORG \
            --build-arg API_HOST=$api_host \
            --env NODE_ENV=development \
            --env NEXT_PUBLIC_MEILISEARCH_HOST=$meili_host \
            --env NEXT_PUBLIC_HOST=$host \
            ;
        
          cd ..

  teardown_on_failure:
    if: ${{ failure() }}
    needs: [env_setup, preview_deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - env:
          prefix: ${{ needs.env_setup.outputs.slug }}
          db_name: ${{ needs.env_setup.outputs.clean_branch }}-staging
        run: |
          flyctl apps destroy -y $prefix-meilisearch || true
          flyctl apps destroy -y $db_name || true
          flyctl apps destroy -y $prefix-django || true
          flyctl apps destroy -y $prefix || true

  # Clean up environment on PR close
  cleanup_environment:
    if: ${{ always() && github.event.action == 'closed' }}
    needs: [env_setup, preview_deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: preview-${{ github.event.number }}
